### PR TITLE
BUG: lazy-import plugin namespace

### LINKED ISSUE #690: AttributeError: module 'imageio.plugins' has no attribute 'freeimage'
Hello,

I have started to get [CI failures](https://github.com/colour-science/colour/runs/4270969224?check_suite_focus=true#step:8:177) today, most likely due to some changes introduced by *imageio 2.11.0*.

I usually install the Freeimage plugin as follows:

```bash
poetry run python -c "import imageio;imageio.plugins.freeimage.download()"
```

Which now raises an exception:

```python
AttributeError: module 'imageio.plugins' has no attribute 'freeimage'
```

### PR DESCRIPTION
**Pull request by FirefoxMetzger**
Closes #690 

This PR reformats `imageio.plugins` so that it, too, can lazy-import plugins. This fixes the bug/regression reported in #690 and also deals with any other cases where people may have been relying on syntax of the form

```python
import imageio

imageio.plugins.<...>
```

---

@almarklein This PR might warrant some discussion. Essentially, we replace the entire `imageio.plugins` module with a class `plugins` class that is defined in said module during import. This relies on a semi-official trick (sanctioned by Guido, but not part of the spec), which we may or may not want to rely on. (see: https://stackoverflow.com/questions/2447353/getattr-on-a-module)

The main point of discussion is if we want to keep this behavior moving into v3, or if we should flag it as deprecated, ask people to use an explicit plugin import (e.g., `import imageio.plugins.freeimage`), and remove it in v3.

### CODE REVIEW

**Comment by almarklein** [comment]
Do we need a class for this? I thought that `__getattr__` was supported on modules now too? Or maybe only in recent versions?

Anyway, I think I prefer `from imageio.plugins import freeimage` for those that need it. People who use that can be concidered power-users anyway. Trying to hide the fact that we're lazily importing seems to add quite a bit of magic+complexity for small gain. my 2ct :)

**Comment by almarklein** [comment]
Looks like my proposal would upset at least [some people](https://github.com/imageio/imageio/issues/690#issuecomment-975851258) :)  -  for the sake of backwards compatibility, let's use the auto-import magic :)

**Comment by FirefoxMetzger** [comment]
> Do we need a class for this? I thought that __getattr__ was supported on modules now too? Or maybe only in recent versions?

As far as I understand, this behavior got removed at some point and has now been reintroduced in python 3.7+. Since we still support python 3.6 I chose to go with the `class` variant, but we can refactor once we drop py3.6 support :)

> Looks like my proposal would upset at least some people :) - and I guess he's right. For the sake of backwards compatibility, let's use the auto-import magic :)

Yes, for the current API we shouldn't break anything and this PR brings back what we lost. 

My question was moreso how we should handle this moving forward, i.e., do we want to officially deprecate things like

```
import imageio; imageio.plugins.<some_plugin>.<some_func>
```

In this case, we should start raising a deprecation warning and ask users to import explicitly. Alternatively, we can keep this behavior under the argument that `imageio.plugins` lazy-import is no more or less magical than `imopen` automatically loading/importing backends.

**Comment by almarklein** [comment]
Recently [this skimage PR](https://github.com/scikit-image/scikit-image/pull/5101) was brought to my attention, where they do something similar. Looks like they dropped 3.7, a snippet from their new `__init__.py`:
```py
from ._shared.version_requirements import ensure_python_version
ensure_python_version((3, 7))

from ._shared import lazy
__getattr__, __lazy_dir__, _ = lazy.attach(__name__, submodules)

**Comment by almarklein** [comment]
> Alternatively, we can keep this behavior under the argument that imageio.plugins lazy-import is no more or less magical than imopen automatically loading/importing backends.

Practicality beats purity. I suspect maintaining this lazy-import logic is less work then doing a deprecation scheme that we need to track. Lets just try this, and if there are no negative effects we keep it.

**Comment by FirefoxMetzger** [comment]
> I suspect maintaining this lazy-import logic is less work then doing a deprecation scheme that we need to track. Lets just try this, and if there are no negative effects we keep it.

Sounds good to me. Then we do it this way.

@almarklein RTR once the last tests have passed. If you have no other suggestions, feel free to merge :)
