### ISSUE TITLE
`mimsave` version issue 

### ISSUE THREAD

**Issue by susuhahnml** [imageio/imageio#973]
With the latest updates my code stoped working. I was using an older version where `mimsave` accepted the argument `fps`. 
I tried to change it to `duration` but now I can't find a version where this works.

- When using the latest version 2.28 I get this error:

```
File "/Users/susana/Education/Phd/Potassco/clingraph/clingraph/gif.py", line 76, in save_gif
    imageio.mimsave(gif_path,
  File "/Users/susana/opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/imageio/v2.py", line 480, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/Users/susana/opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/imageio/plugins/pillow.py", line 331, in write
    ndimage = np.stack(ndimage, axis=0)
  File "<__array_function__ internals>", line 200, in stack
  File "/Users/susana/opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/numpy/core/shape_base.py", line 464, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

Which was not there before.

- When using the latest version 2.27 I get an error since duration is `1000` (According to the formula on the error log since my fps was 1):

```
clingraph/gif.py:76: in save_gif
    imageio.mimsave(gif_path,
../../../../opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/imageio/v2.py:331: in mimwrite
    return file.write(ims, **kwargs)
../../../../opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/imageio/core/legacy_plugin_wrapper.py:216: in write
    writer.append_data(ndimage)
../../../../opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/imageio/core/format.py:589: in append_data
    return self._append_data(im, total_meta)
../../../../opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/imageio/plugins/pillowmulti.py:84: in _append_data
    self._writer.add_image(im, duration, dispose)
../../../../opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/imageio/plugins/pillowmulti.py:141: in add_image
    self.write_image(im_pil, palette, rect, duration, dispose)
../../../../opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/imageio/plugins/pillowmulti.py:176: in write_image
    graphext = self.getGraphicsControlExt(duration, dispose)
../../../../opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/imageio/plugins/pillowmulti.py:270: in getGraphicsControlExt
    bb += intToBin(int(duration * 100 + 0.5))  # in 100th of seconds
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

i = 100000

    def intToBin(i):
>       return i.to_bytes(2, byteorder="little")
E       OverflowError: int too big to convert

../../../../opt/anaconda3/envs/clingraph/lib/python3.9/site-packages/imageio/plugins/pillowmulti.py:90: OverflowError
```

I also tried to use an oder version but there seams to be a misssmatch between coda and pip, since my pip installation for earlier versions (like 2.16) is accepting `fps` but the conda for `2.16` expects `duration`.

Any suggestions how to treat this?

**Comment by FirefoxMetzger** [comment]
> With the latest updates my code stoped working. I was using an older version where mimsave accepted the argument fps.
I tried to change it to duration but now I can't find a version where this works

When I last tried ([xref](https://github.com/imageio/imageio/issues/975#issuecomment-1522359399)), the `duration` kwarg was working as intended, so there is probably something amiss in how you are using it. Unfortunately, it is hard to say what is wrong without seeing more context of what you are trying to achieve.

Both exceptions that you shared relate to different things and are both unrelated with `duration`. The first fails because you are trying to save images with different shapes in the same GIF and the second fails because you are trying to palettize an image with a color palette of more than 256 colors.

Could you make a small example that I can use to understand what you are doing? Perhaps something that allows me to reproduce the issue so I can see where and how things break and suggest a way to fix them?

**Comment by susuhahnml** [comment]
Thank you for the response. I am mostly just looking for a stable version for conda and pip to work. 

Here a pice of code to show how I am using it:
```
        images = []
        for k in all_keys[model_n]:
            images.append(imageio.imread(os.path.join(images_dir, img_path)))
        os.makedirs(os.path.dirname(gif_path), exist_ok=True)
        duration = int(1000 * 1/fps)
        imageio.mimsave(gif_path,
                        images, duration=duration)
```

It could be the case that the images are different sizes. In a previous version this used to be ok, is there a way around it now? Or what older version could I use? My requirement used to be `imageio>=2.14z but I am unsure which one was installed. Now I can't seem to find a stable option to keep the code using the fps, or how to update it.

Thank you again for the response :)

**Comment by FirefoxMetzger** [comment]
> It could be the case that the images are different sizes. In a previous version this used to be ok, is there a way around it now?

I doubt that differently-sized images were ever accepted by ImageIO when writing GIF (with the exception of a bug in pyav that has since been fixed, but that plugin has been unavailable in the v2 API before v2.28). 

GIF requires all frames to have the same size, so we would have to convert differently-sized images into the same size. Unfortunately, there are many ways to do this (scale everything up, scale everything down, crop, pad, ...) all with internal variations. They all have different results and there is no way for ImageIO to guess which one you would prefer so we can't choose a good default. Instead, you have to convert the images into the same shape yourself and then give them to ImageIO - and it has always been that way.

> Thank you for the response. I am mostly just looking for a stable version for conda and pip to work.

In general, I'd recommend you always use the latest version of ImageIO and the latest API version (v3) unless there is a bug that affects a feature that you need and thus blocks you from that version. This way, you will use the same version as the developers of the library (like me) and it becomes much easier to provide help, because we can more easily reproduce what you are doing.

> I am unsure which one was installed

You are on linux or mac, so you should be able to check for the installed version via `pip freeze | grep imageio`.

> Now I can't seem to find a stable option to keep the code using the fps, or how to update it.

Your snippet looks good, and if I run it (with some additions to make it executable), it produces a GIF with the duration I specify:

```python
import imageio.v2 as iio
import numpy as np
import os

rng = np.random.default_rng()

# generate some solid images in random colors for testing
for idx in range(10):
    random_color = rng.integers(0, 255, size=3, dtype=np.uint8)
    image = np.full((100, 100, 3), random_color, dtype=np.uint8)
    iio.imwrite(f"_imgs/image{idx}.png", image)

# your snippet (with slight modifications to make it executable)
gif_path = "_imgs/output.gif"
images_dir = "_imgs"
fps = 1  # show each image for 1 second

images = []
for idx in range(10):
    images.append(iio.imread(os.path.join("_imgs", f"image{idx}.png")))

os.makedirs(os.path.dirname(gif_path), exist_ok=True)
duration = int(1000 * 1 / fps)
iio.mimsave(gif_path, images, duration=duration, loop=0)

```

![output](https://user-images.githubusercontent.com/4402489/234565146-95a4966a-b7d2-4384-9243-27818f90bfd4.gif)

**Comment by SimiPixel** [comment]
Same issue:
- Code that works with `2.27.0`; Pillow=9.5.0
- Upgrade to `2.28.0` same Pillow, and tests fail with 
> TypeError: The keyword `fps` is no longer supported. Use `duration` instead, e.g. `fps=50`==`duration=20`
- Replaced `fps` with `duration` as suggested. Then tests fail with 
> TypeError: FfmpegFormat.Writer._open() got an unexpected keyword argument `duration`
- Downgrading to `2.27` and tests work again.

**Comment by FirefoxMetzger** [comment]
@SimiPixel I will have to say the same thing as I said before. It's hard for me to say what causes the problem without seeing either the code you are trying to run or an example snippet that can reproduce the faulty behavior. 

> Upgrade to 2.28.0 same Pillow, and tests fail with

Since you mention a test that fails, are you able to share this test? Maybe this way we can track down the problem.

--- 

I'm happy to help and fix any regression in ImageIO (sounds like this is happening here); however, I need to know where the problem is before I can go and fix it 😅

**Comment by SimiPixel** [comment]
If you don't mind creating an additional e.g. conda environment for testing purposes, then you can install the following package [click](https://github.com/SimiPixel/x_xy_v2).
Then, the `test_render.py` is the test i was referring to. :)
