### ISSUE TITLE
imageio v2.33.0 requieres Pillow>=9.1.0 for GIFs

### ISSUE THREAD

**Issue by sitic** [imageio/imageio#1052]
When using Pillow<9.1.0 (`pip install pillow==9.0.1 imageio`) importing a GIF fails:
```
import imageio.v3 as iio3
iio3.imread('https://upload.wikimedia.org/wikipedia/commons/8/8f/Example.gif')
```
error:
```
Traceback (most recent call last):
  File "imageio/v3.py", line 54, in imread
    return np.asarray(img_file.read(**call_kwargs))
  File "imageio/plugins/pillow.py", line 238, in read
    GifImagePlugin.LoadingStrategy.RGB_AFTER_DIFFERENT_PALETTE_ONLY
AttributeError: module 'PIL.GifImagePlugin' has no attribute 'LoadingStrategy'
```
`PIL.GifImagePlugin.LoadingStrategy` was added to Pillow in v9.1.0. This works with `imageio<2.33`.

**Comment by Pandede** [comment]
Importing `LoadingStrategy` is due to this issue https://github.com/imageio/imageio/issues/1030 and I fixed it according to this PR https://github.com/python-pillow/Pillow/pull/6150.

I may make a PR to lock the mode to `RGB` when loading the GIF if `Pillow<9.1.0` (same as set `LoadingStrategy` to `RGB_ALWAYS`).
